// This file is auto-generated by @hey-api/openapi-ts

import { createClient, createConfig, type OptionsLegacyParser, formDataBodySerializer } from '@hey-api/client-axios';
import type { UploadTextTaxInfoTextPostData, UploadTextTaxInfoTextPostError, UploadTextTaxInfoTextPostResponse, UploadFileTaxInfoFilePostData, UploadFileTaxInfoFilePostError, UploadFileTaxInfoFilePostResponse } from './types.gen';

export const client = createClient(createConfig());

/**
 * Upload Text
 */
export const uploadTextTaxInfoTextPost = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<UploadTextTaxInfoTextPostData, ThrowOnError>) => {
    return (options?.client ?? client).post<UploadTextTaxInfoTextPostResponse, UploadTextTaxInfoTextPostError, ThrowOnError>({
        ...options,
        url: '/tax-info/text'
    });
};

/**
 * Upload File
 */
export const uploadFileTaxInfoFilePost = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<UploadFileTaxInfoFilePostData, ThrowOnError>) => {
    return (options?.client ?? client).post<UploadFileTaxInfoFilePostResponse, UploadFileTaxInfoFilePostError, ThrowOnError>({
        ...options,
        ...formDataBodySerializer,
        headers: {
            'Content-Type': null,
            ...options?.headers
        },
        url: '/tax-info/file'
    });
};